<?php
declare(strict_types=1);

namespace Terazi;

final class Lang
{
    private const STRINGS = [
        'en' => [
            'tagline' => 'One story, read from every side',
            'label.gov' => 'Pro-government',
            'label.ind' => 'Independent',
            'label.opp' => 'Pro-opposition',
            'label.gov.short' => 'Pro-gov.',
            'label.ind.short' => 'Indep.',
            'label.opp.short' => 'Pro-opp.',
            'nav.front' => 'Front page',
            'nav.menu' => 'Menu',
            'nav.news' => 'Latest news',
            'nav.recap' => 'Daily recap',
            'random' => 'Random story',
            'random.again' => 'Another random story',
            'recap.title' => 'Daily recap',
            'recap.intro' => 'The day\'s most important stories, ranked by how many outlets covered them, and the ones only one side reported.',
            'recap.day' => 'Day',
            'recap.today' => 'Today',
            'recap.yesterday' => 'Yesterday',
            'recap.stat.articles' => 'articles from %d outlets',
            'recap.stat.multi' => 'stories covered by two or more outlets',
            'recap.stat.blind' => 'one-sided stories',
            'recap.top' => 'Most covered',
            'recap.blind' => 'One-sided',
            'recap.none' => 'No story has been covered by more than one outlet yet on this day.',
            'article' => '%d article',
            'recap.panel.outlets' => 'Articles per outlet',
            'recap.panel.multi' => 'Stories covered by two or more outlets',
            'recap.panel.blind' => 'One-sided stories',
            'recap.close' => 'Close',
            'nav.blindspots' => 'Blindspots',
            'nav.sources' => 'Outlets',
            'updated' => 'Updated %s',
            'never_updated' => 'No feeds fetched yet',
            'outlets' => '%d outlets',
            'outlet' => '1 outlet',
            'articles' => '%d articles',
            'compare' => 'Compare %d outlets',
            'blindspots.title' => 'Blindspots',
            'blindspots.intro' => 'Stories that only one side is reporting.',
            'blindspots.only.gov' => 'Only pro-government outlets',
            'blindspots.only.opp' => 'Only pro-opposition outlets',
            'blindspots.none' => 'No one-sided stories right now. Every story with three or more outlets has coverage from both sides.',
            'blindspots.more' => 'All blindspots',
            'brief.title' => 'In brief',
            'brief.intro' => 'Reported by one outlet so far.',
            'more.title' => 'More stories',
            'news.title' => 'Latest news',
            'news.intro' => 'Every headline from every outlet, newest first. Stories several outlets are covering link to the side-by-side comparison.',
            'news.filter' => 'Filter by side',
            'news.all' => 'All outlets',
            'news.none' => 'No articles yet.',
            'news.pages' => 'Pages',
            'news.newer' => 'Newer',
            'news.older' => 'Older',
            'story.back' => 'Front page',
            'story.first' => 'First reported %s',
            'story.latest' => 'latest %s',
            'story.none' => 'No coverage',
            'story.notyet' => 'No matching article from:',
            'story.sides' => 'Jump to a side',
            'scale.caption' => 'The beam tips toward the side with more outlets covering the story.',
            'sources.title' => 'Outlets and labels',
            'sources.intro' => 'Each outlet carries one of three labels, with a short note on why: who owns it and what its editorial line is. Labels are a starting point, not a verdict; ownership and editorial lines change often. Notes last checked in October 2026.',
            'sources.def.gov' => 'Editorial line generally supports the governing alliance.',
            'sources.def.ind' => 'Not aligned with either camp; free and foreign-funded public newsrooms.',
            'sources.def.opp' => 'Editorial line generally supports opposition parties.',
            'sources.last24' => '%d articles in the last 24 hours',
            'sources.ok' => 'Feed working',
            'sources.error' => 'Feed not responding at the moment',
            'sources.never' => 'Not fetched yet',
            'empty.title' => 'Nothing to compare yet',
            'empty.body' => 'The first headlines will appear here shortly.',
            'ago.now' => 'just now',
            'ago.min' => '%d min ago',
            'ago.hour' => '%d h ago',
            'ago.day' => '%d d ago',
            'footer' => 'Terazi groups headlines from public RSS feeds. Headlines and links belong to their outlets.',
            'fresh' => 'New stories are in.',
            'fresh.reload' => 'Reload',
            'error.title' => 'Something went wrong',
            'error.body' => 'This page can’t be shown right now. Please try again in a moment.',
            'search.title' => 'Search',
            'search.title.q' => 'Search: %s',
            'search.label' => 'Search headlines',
            'search.placeholder' => 'Search headlines',
            'search.button' => 'Search',
            'search.note' => 'Searches the headlines and summaries of the last %d days. Accents and capitals don\'t matter.',
            'search.private' => 'Searches stay in your browser.',
            'search.count' => '%d articles match “%s”',
            'search.one' => '1 article matches “%s”',
            'search.none' => 'Nothing matches. Try fewer or shorter words: “seçim” also finds “seçimlerde”.',
            'search.nojs' => 'Search works in your browser and needs JavaScript. Without it, use Latest news.',
            'search.loading' => 'Loading the headlines…',
            'search.failed' => 'The headlines couldn\'t be loaded. Reload the page to try again.',
            'search.more' => 'Show more',
            'search.more_in' => '+%d more matching headlines in this story',
            'news.more_in_search' => 'Older headlines are not listed here, but search finds them.',
            'random.going' => 'Opening a random story…',
            'random.none' => 'No story has been covered by more than one outlet today yet.',
            'notfound.title' => 'Page not found',
            'notfound.body' => 'This page doesn\'t exist (any more). Story pages are rebuilt with every update and old stories are removed, so the story you were looking for may have been regrouped.',
            'privacy.link' => 'Privacy, KVKK and contact',
            'privacy.title' => 'Privacy and cookies',
            'privacy.h1' => 'Privacy, cookies and personal data notice',
            'privacy.intro' => 'Short version: Terazi doesn\'t know who you are and doesn\'t try to find out. There are no accounts, no cookies, no analytics, no ads and no trackers, and the site\'s owner receives nothing about your visit. The site is hosted on GitHub Pages, and GitHub records visitors\' IP addresses for security (details below). This notice is given under Article 10 of the Turkish Personal Data Protection Law No. 6698 (KVKK).',
            'privacy.controller.h' => 'Data controller and contact',
            'privacy.controller.p' => 'The data controller under Law No. 6698 is the person who runs this site:',
            'privacy.controller.missing' => 'The site owner\'s details haven\'t been added yet.',
            'privacy.name' => 'Name',
            'privacy.email' => 'Email',
            'privacy.address' => 'Address',
            'privacy.host' => 'Hosting',
            'privacy.data.h' => 'What personal data is processed',
            'privacy.data.p' => 'There is no sign-up, no account, no form and no cookies. When you open a page, your browser sends the technical details it sends to every website (your IP address, the address of the page you asked for, and your browser\'s name and version) to GitHub\'s servers, which host the site. The site\'s owner does not receive, see or keep these details. The pages are ready-made files built from the news; the site\'s database holds only news articles from the outlets\' public RSS feeds.',
            'privacy.github.h' => 'Hosting: GitHub Pages',
            'privacy.github.p' => 'The site is hosted on GitHub Pages, a service run by GitHub, Inc. in the USA. According to GitHub\'s own documentation, when a GitHub Pages site is visited, the visitor\'s IP address is logged and stored for security purposes. GitHub keeps these records; the site\'s owner can\'t access, see or delete them. How GitHub handles them is explained in GitHub\'s own documents:',
            'privacy.github.statement' => 'GitHub General Privacy Statement',
            'privacy.github.pages' => 'About GitHub Pages: data collection',
            'privacy.purpose.h' => 'Purpose, legal basis and how it is collected',
            'privacy.purpose.p' => 'The technical details are processed on GitHub\'s servers so that the page you asked for can be sent to you; GitHub also records IP addresses for its own security purposes. They are collected automatically, electronically, through your browser when you visit. The legal basis for processing them to send the page is Article 5(2)(f) of the KVKK: processing is necessary for the legitimate interest of the data controller in publishing the site, without harming your fundamental rights and freedoms. The site\'s owner never uses them for profiling, advertising, statistics or anything else.',
            'privacy.transfer.h' => 'Transfers and processing abroad',
            'privacy.transfer.p' => 'The site\'s owner doesn\'t share, sell or pass on your personal data to anyone. When you open the site, however, your browser connects directly to GitHub\'s servers. GitHub is a US company, and its servers and content delivery network are outside Türkiye, so the technical details above are processed abroad, mainly in the USA. This may count as a transfer of personal data abroad under Article 9 of the KVKK.',
            'privacy.transfer.logs' => 'Your internet provider may also keep traffic records under its own obligations under Law No. 5651. Those records are its responsibility and are not passed to this site.',
            'privacy.retention.h' => 'How long it is kept',
            'privacy.retention.p' => 'The site\'s owner keeps no personal data. How long GitHub keeps its security records depends on GitHub\'s own policies; GitHub\'s privacy statement gives no fixed period for them.',
            'privacy.cookies.h' => 'Cookies',
            'privacy.cookies.p' => 'Terazi uses no cookies at all, not even "strictly necessary" ones, and GitHub Pages sets none on this site either. That is why there is no cookie banner and nothing to consent to under the Personal Data Protection Authority\'s Cookie Guidelines. Local storage and similar ways of keeping data in your browser aren\'t used either. Like any website, your browser may keep a cached copy of pages to load them faster; you can clear that in your browser settings.',
            'privacy.search.h' => 'Search',
            'privacy.search.p' => 'Search happens entirely in your browser. The search page downloads a file of recent headlines once and searches it on your device; the words you type are never sent to any server, GitHub included. They sit in the address after the "#" sign, a part browsers never send to servers. They do stay in your own browser history; use a private window if you don\'t want that.',
            'privacy.third.h' => 'No other third parties',
            'privacy.third.p' => 'Your browser only connects to GitHub\'s servers, and pages tell it not to connect anywhere else. Fonts are hosted on the site, and there are no news photos, embedded videos, social media buttons, ad networks or analytics services.',
            'privacy.links.h' => 'Links to outlets',
            'privacy.links.p' => 'Headlines link to the outlets\' own websites, which have their own privacy policies and cookies. Terazi has no control over them. Links are opened without a referrer, so the outlet isn\'t told that you came from here or which page you were on.',
            'privacy.fresh.h' => 'The "new stories" check',
            'privacy.fresh.p' => 'While a page is open, it checks a small file on the site (updated.json) every two minutes to see whether new stories have arrived, so it can offer a reload. The request contains nothing about you, but like every request it reaches GitHub\'s servers. It is skipped when your browser is in data saver mode.',
            'privacy.rights.h' => 'Your rights under the KVKK',
            'privacy.rights.p' => 'Under Article 11 of the KVKK you have the right to:',
            'privacy.rights.a' => 'learn whether your personal data is processed;',
            'privacy.rights.b' => 'request information about it if it is;',
            'privacy.rights.c' => 'learn the purpose of the processing and whether it is used for that purpose;',
            'privacy.rights.ç' => 'know the third parties in Türkiye or abroad to whom it is transferred;',
            'privacy.rights.d' => 'ask for it to be corrected if it is incomplete or wrong;',
            'privacy.rights.e' => 'ask for it to be erased or destroyed under the conditions in Article 7;',
            'privacy.rights.f' => 'ask for corrections, erasures and destructions to be passed on to the third parties it was transferred to;',
            'privacy.rights.g' => 'object to an outcome against you that arises from analysis exclusively by automated systems;',
            'privacy.rights.ğ' => 'claim compensation if you suffer damage because it was processed unlawfully.',
            'privacy.apply.h' => 'How to apply',
            'privacy.apply.p' => 'Under the Communiqué on the Procedures and Principles of Application to the Data Controller, you can apply in writing to the postal address above, or by registered electronic mail (KEP), secure electronic signature or mobile signature; applications by ordinary email to the address above are answered too. Please include your name and surname, your signature (for written applications), your Turkish ID number (or, if you are not a Turkish citizen, your nationality and passport or ID number), your address for notifications, your email and phone number if you have them, and what you are asking for. You will get a free answer within 30 days at the latest. Since the site keeps no personal data, we will most likely find no record about you, but every application is answered.',
            'privacy.apply.github' => 'Requests about the records GitHub keeps have to be sent to GitHub directly, as the site\'s owner can\'t access them.',
            'privacy.apply.complaint' => 'If your application is refused, you find the answer insufficient, or it isn\'t answered in time, you can complain to the Personal Data Protection Board within 30 days of learning the answer, and in any case within 60 days of applying (KVKK Article 14).',
            'privacy.content.h' => 'Content and terms of use',
            'privacy.content.p' => 'Headlines and summaries belong to their outlets. Terazi shows short excerpts from public RSS feeds and always links to the original article; articles are deleted after a few days. The pro-government, independent and pro-opposition labels are an editorial judgement, not a statement of fact; the Outlets page explains each one. Stories are grouped automatically and sometimes get it wrong. The site is provided as is, free of charge, without guarantees.',
            'privacy.changes.h' => 'Changes',
            'privacy.changes.p' => 'If the way this site handles visitors ever changes, this notice will be updated before the change takes effect.',
            'privacy.updated' => 'Last updated: 5 October 2026.',
        ],
        'tr' => [
            'tagline' => 'Aynı haber, her taraftan',
            'label.gov' => 'İktidar yanlısı',
            'label.ind' => 'Bağımsız',
            'label.opp' => 'Muhalefet yanlısı',
            'label.gov.short' => 'İktidar',
            'label.ind.short' => 'Bağımsız',
            'label.opp.short' => 'Muhalefet',
            'nav.front' => 'Ana sayfa',
            'nav.menu' => 'Menü',
            'nav.news' => 'Son haberler',
            'nav.recap' => 'Günün özeti',
            'random' => 'Rastgele haber',
            'random.again' => 'Başka bir rastgele haber',
            'recap.title' => 'Günün özeti',
            'recap.intro' => 'Günün en önemli haberleri, kaç yayının işlediğine göre sıralı; bir de yalnızca tek tarafın haber yaptıkları.',
            'recap.day' => 'Gün',
            'recap.today' => 'Bugün',
            'recap.yesterday' => 'Dün',
            'recap.stat.articles' => 'haber, %d yayın organından',
            'recap.stat.multi' => 'haber iki veya daha fazla yayında',
            'recap.stat.blind' => 'tek taraflı haber',
            'recap.top' => 'En çok işlenenler',
            'recap.blind' => 'Tek taraflı',
            'recap.none' => 'Bu gün henüz birden fazla yayında çıkan bir haber yok.',
            'article' => '%d haber',
            'recap.panel.outlets' => 'Yayın organına göre haberler',
            'recap.panel.multi' => 'İki veya daha fazla yayında çıkan haberler',
            'recap.panel.blind' => 'Tek taraflı haberler',
            'recap.close' => 'Kapat',
            'nav.blindspots' => 'Kör noktalar',
            'nav.sources' => 'Yayın organları',
            'updated' => 'Güncelleme %s',
            'never_updated' => 'Henüz haber çekilmedi',
            'outlets' => '%d yayın organı',
            'outlet' => '1 yayın organı',
            'articles' => '%d haber',
            'compare' => '%d yayın organını karşılaştır',
            'blindspots.title' => 'Kör noktalar',
            'blindspots.intro' => 'Yalnızca bir tarafın haber yaptığı konular.',
            'blindspots.only.gov' => 'Yalnızca iktidar yanlısı yayınlar',
            'blindspots.only.opp' => 'Yalnızca muhalefet yanlısı yayınlar',
            'blindspots.none' => 'Şu an tek taraflı bir haber yok. Üç ve daha fazla yayında çıkan her haber iki taraftan da işlenmiş.',
            'blindspots.more' => 'Tüm kör noktalar',
            'brief.title' => 'Kısa kısa',
            'brief.intro' => 'Şimdilik tek bir yayında çıkan haberler.',
            'more.title' => 'Diğer haberler',
            'news.title' => 'Son haberler',
            'news.intro' => 'Tüm yayın organlarındaki başlıklar, en yeniden eskiye. Birden fazla yayında çıkan haberler karşılaştırma sayfasına bağlanır.',
            'news.filter' => 'Tarafa göre süz',
            'news.all' => 'Tüm yayınlar',
            'news.none' => 'Henüz haber yok.',
            'news.pages' => 'Sayfalar',
            'news.newer' => 'Daha yeni',
            'news.older' => 'Daha eski',
            'story.back' => 'Ana sayfa',
            'story.first' => 'İlk haber %s',
            'story.latest' => 'son %s',
            'story.none' => 'Haber yok',
            'story.notyet' => 'Eşleşen haberi olmayanlar:',
            'story.sides' => 'Tarafa git',
            'scale.caption' => 'Terazi, haberi daha çok yayının işlediği tarafa eğilir.',
            'sources.title' => 'Yayın organları ve etiketler',
            'sources.intro' => 'Her yayın üç etiketten birini ve nedenini anlatan kısa bir notu taşır: sahibi kim, yayın çizgisi ne. Etiketler kesin hüküm değil, bir başlangıç noktasıdır; sahiplik ve yayın çizgileri sık değişir. Notlar en son Ekim 2026\'da kontrol edildi.',
            'sources.def.gov' => 'Yayın çizgisi genel olarak iktidar ittifakını destekler.',
            'sources.def.ind' => 'İki kampa da bağlı değil; bağımsız ve yabancı kamu yayıncıları.',
            'sources.def.opp' => 'Yayın çizgisi genel olarak muhalefet partilerini destekler.',
            'sources.last24' => 'Son 24 saatte %d haber',
            'sources.ok' => 'Akış çalışıyor',
            'sources.error' => 'Akış şu an alınamıyor',
            'sources.never' => 'Henüz çekilmedi',
            'empty.title' => 'Henüz karşılaştırılacak haber yok',
            'empty.body' => 'İlk başlıklar birazdan burada olacak.',
            'ago.now' => 'az önce',
            'ago.min' => '%d dk önce',
            'ago.hour' => '%d sa önce',
            'ago.day' => '%d gün önce',
            'footer' => 'Terazi, herkese açık RSS akışlarındaki başlıkları gruplar. Başlıklar ve bağlantılar yayın organlarına aittir.',
            'fresh' => 'Yeni haberler geldi.',
            'fresh.reload' => 'Yenile',
            'error.title' => 'Bir sorun çıktı',
            'error.body' => 'Bu sayfa şu an gösterilemiyor. Lütfen biraz sonra yeniden deneyin.',
            'search.title' => 'Arama',
            'search.title.q' => 'Arama: %s',
            'search.label' => 'Başlıklarda ara',
            'search.placeholder' => 'Başlıklarda ara',
            'search.button' => 'Ara',
            'search.note' => 'Son %d günün başlık ve özetlerinde arar. Büyük-küçük harf ve Türkçe karakterler fark etmez.',
            'search.private' => 'Aramalar tarayıcınızda kalır.',
            'search.count' => '“%2$s” için %1$d haber bulundu',
            'search.one' => '“%s” için 1 haber bulundu',
            'search.none' => 'Sonuç yok. Daha az veya daha kısa kelime deneyin: “seçim” yazınca “seçimlerde” de bulunur.',
            'search.nojs' => 'Arama tarayıcınızda çalışır ve JavaScript gerektirir. JavaScript kapalıysa Son haberler sayfasını kullanın.',
            'search.loading' => 'Başlıklar yükleniyor…',
            'search.failed' => 'Başlıklar yüklenemedi. Yeniden denemek için sayfayı yenileyin.',
            'search.more' => 'Daha fazla göster',
            'search.more_in' => 'Bu olayda eşleşen %d haber daha',
            'news.more_in_search' => 'Daha eski başlıklar burada listelenmez, ama arama onları da bulur.',
            'random.going' => 'Rastgele bir habere gidiliyor…',
            'random.none' => 'Bugün henüz birden fazla yayında çıkan bir haber yok.',
            'notfound.title' => 'Sayfa bulunamadı',
            'notfound.body' => 'Bu sayfa yok ya da artık yok. Haber sayfaları her güncellemede yeniden oluşturulur ve eski haberler silinir; aradığınız haber yeniden gruplanmış olabilir.',
            'privacy.link' => 'Gizlilik, KVKK ve iletişim',
            'privacy.title' => 'Gizlilik ve çerezler',
            'privacy.h1' => 'Gizlilik, çerezler ve KVKK aydınlatma metni',
            'privacy.intro' => 'Kısaca: Terazi kim olduğunuzu bilmez ve öğrenmeye çalışmaz. Üyelik, çerez, ziyaretçi istatistiği, reklam ya da izleyici yoktur ve site sahibi ziyaretinizle ilgili hiçbir bilgi almaz. Site GitHub Pages\'te barındırılır; GitHub, ziyaretçilerin IP adreslerini güvenlik amacıyla kaydeder (ayrıntılar aşağıda). Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu\'nun (KVKK) 10. maddesi ve Aydınlatma Yükümlülüğünün Yerine Getirilmesinde Uyulacak Usul ve Esaslar Hakkında Tebliğ uyarınca hazırlanmıştır.',
            'privacy.controller.h' => 'Veri sorumlusu ve iletişim',
            'privacy.controller.p' => '6698 sayılı Kanun kapsamında veri sorumlusu, bu siteyi işleten kişidir:',
            'privacy.controller.missing' => 'Site sahibinin bilgileri henüz eklenmedi.',
            'privacy.name' => 'Ad soyad / unvan',
            'privacy.email' => 'E-posta',
            'privacy.address' => 'Adres',
            'privacy.host' => 'Barındırma',
            'privacy.data.h' => 'İşlenen kişisel veriler',
            'privacy.data.p' => 'Sitede üyelik, hesap, form ya da çerez yoktur. Bir sayfayı açtığınızda tarayıcınız, her siteye gönderdiği teknik bilgileri (IP adresiniz, açtığınız sayfanın adresi ve tarayıcınızın adı ve sürümü) siteyi barındıran GitHub\'ın sunucularına gönderir. Site sahibi bu bilgileri almaz, göremez ve saklamaz. Sayfalar, haberlerden önceden hazırlanmış dosyalardır; sitenin veritabanında yalnızca yayın organlarının herkese açık RSS akışlarından alınan haberler bulunur.',
            'privacy.github.h' => 'Barındırma: GitHub Pages',
            'privacy.github.p' => 'Site, GitHub, Inc. (ABD) tarafından işletilen GitHub Pages hizmetinde barındırılır. GitHub\'ın kendi belgelerine göre bir GitHub Pages sitesi ziyaret edildiğinde ziyaretçinin IP adresi güvenlik amacıyla kaydedilir ve saklanır. Bu kayıtları GitHub tutar; site sahibi bunlara erişemez, bunları göremez ya da silemez. GitHub\'ın bu bilgileri nasıl işlediği GitHub\'ın kendi belgelerinde açıklanır:',
            'privacy.github.statement' => 'GitHub Genel Gizlilik Bildirimi (İngilizce)',
            'privacy.github.pages' => 'GitHub Pages hakkında: veri toplama (İngilizce)',
            'privacy.purpose.h' => 'İşleme amacı, hukuki sebebi ve toplama yöntemi',
            'privacy.purpose.p' => 'Teknik bilgiler, istediğiniz sayfanın size iletilebilmesi için GitHub\'ın sunucularında işlenir; GitHub ayrıca IP adreslerini kendi güvenlik amaçlarıyla kaydeder. Bilgiler, siteyi ziyaret ettiğinizde tarayıcınız aracılığıyla, otomatik yollarla ve elektronik ortamda toplanır. Sayfanın iletilmesi için işlenmelerinin hukuki sebebi, KVKK\'nın 5. maddesinin 2. fıkrasının (f) bendi uyarınca, temel hak ve özgürlüklerinize zarar vermemek kaydıyla, veri sorumlusunun siteyi yayınlayabilmesine ilişkin meşru menfaati için işlemenin zorunlu olmasıdır. Site sahibi bu bilgileri profil çıkarmak, reklam, istatistik ya da başka herhangi bir amaçla kullanmaz.',
            'privacy.transfer.h' => 'Aktarım ve yurt dışında işleme',
            'privacy.transfer.p' => 'Site sahibi kişisel verilerinizi kimseyle paylaşmaz, satmaz ve kimseye aktarmaz. Ancak siteyi açtığınızda tarayıcınız doğrudan GitHub\'ın sunucularına bağlanır. GitHub bir ABD şirketidir; sunucuları ve içerik dağıtım ağı Türkiye dışındadır. Bu nedenle yukarıdaki teknik bilgiler yurt dışında, başta ABD\'de işlenir. Bu, KVKK\'nın 9. maddesi kapsamında kişisel verilerin yurt dışına aktarılması sayılabilir.',
            'privacy.transfer.logs' => 'İnternet erişim sağlayıcınız da 5651 sayılı Kanun\'dan doğan kendi yükümlülükleri gereğince trafik kayıtları tutabilir. Bu kayıtlar onun sorumluluğundadır ve bu siteye iletilmez.',
            'privacy.retention.h' => 'Saklama süresi',
            'privacy.retention.p' => 'Site sahibi hiçbir kişisel veri saklamaz. GitHub\'ın güvenlik kayıtlarını ne kadar sakladığı GitHub\'ın kendi politikalarına bağlıdır; GitHub\'ın gizlilik bildirimi bunun için belirli bir süre vermez.',
            'privacy.cookies.h' => 'Çerezler',
            'privacy.cookies.p' => 'Terazi hiç çerez kullanmaz, "zorunlu" çerezler de dahil; GitHub Pages de bu sitede çerez kullanmaz. Bu yüzden çerez uyarısı yoktur ve Kişisel Verileri Koruma Kurumu\'nun Çerez Uygulamaları Hakkında Rehberi kapsamında onay verilecek bir şey de yoktur. Tarayıcınızın yerel depolama alanı ya da tarayıcıda veri saklamanın başka bir yolu da kullanılmaz. Her sitede olduğu gibi tarayıcınız, sayfaları daha hızlı açmak için önbelleğe alabilir; bunu tarayıcı ayarlarından temizleyebilirsiniz.',
            'privacy.search.h' => 'Arama',
            'privacy.search.p' => 'Arama tamamen tarayıcınızda yapılır. Arama sayfası son günlerin haber başlıklarını içeren bir dosyayı bir kez indirir ve aramayı cihazınızda yapar; yazdığınız kelimeler hiçbir sunucuya, GitHub\'a da gönderilmez. Kelimeler adres çubuğunda "#" işaretinden sonra durur; tarayıcılar bu kısmı sunuculara göndermez. Kendi tarayıcı geçmişinizde ise kalır; istemiyorsanız gizli pencere kullanın.',
            'privacy.third.h' => 'Başka üçüncü taraf yok',
            'privacy.third.p' => 'Tarayıcınız yalnızca GitHub\'ın sunucularına bağlanır; sayfalar da tarayıcınıza başka hiçbir adrese bağlanmamasını söyler. Yazı tipleri sitede barındırılır; haber fotoğrafı, gömülü video, sosyal medya düğmesi, reklam ağı ya da istatistik hizmeti yoktur.',
            'privacy.links.h' => 'Yayın organlarına bağlantılar',
            'privacy.links.p' => 'Başlıklar, yayın organlarının kendi sitelerine bağlanır; o sitelerin kendi gizlilik politikaları ve çerezleri vardır ve Terazi\'nin bunlar üzerinde bir denetimi yoktur. Bağlantılar yönlendiren bilgisi olmadan açılır; yayın organına buradan ya da hangi sayfadan geldiğiniz bildirilmez.',
            'privacy.fresh.h' => '"Yeni haber" denetimi',
            'privacy.fresh.p' => 'Bir sayfa açıkken, yenilemeyi önerebilmek için iki dakikada bir sitedeki küçük bir dosyaya (updated.json) bakarak yeni haber gelip gelmediğini denetler. Bu istek sizinle ilgili hiçbir bilgi içermez, ama her istek gibi GitHub\'ın sunucularına ulaşır. Tarayıcınız veri tasarrufu modundaysa hiç yapılmaz.',
            'privacy.rights.h' => 'KVKK kapsamındaki haklarınız',
            'privacy.rights.p' => 'KVKK\'nın 11. maddesi uyarınca şu haklara sahipsiniz:',
            'privacy.rights.a' => 'kişisel verilerinizin işlenip işlenmediğini öğrenme,',
            'privacy.rights.b' => 'işlenmişse buna ilişkin bilgi talep etme,',
            'privacy.rights.c' => 'işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,',
            'privacy.rights.ç' => 'yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme,',
            'privacy.rights.d' => 'eksik veya yanlış işlenmişse düzeltilmesini isteme,',
            'privacy.rights.e' => 'KVKK\'nın 7. maddesindeki şartlar çerçevesinde silinmesini veya yok edilmesini isteme,',
            'privacy.rights.f' => 'düzeltme, silme ve yok etme işlemlerinin verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,',
            'privacy.rights.g' => 'işlenen verilerin münhasıran otomatik sistemlerle analiz edilmesi sonucunda aleyhinize bir sonuç çıkmasına itiraz etme,',
            'privacy.rights.ğ' => 'kanuna aykırı işlenmesi sebebiyle zarara uğramanız hâlinde zararın giderilmesini talep etme.',
            'privacy.apply.h' => 'Başvuru',
            'privacy.apply.p' => 'Bu haklarınızı kullanmak için, Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ\'e uygun olarak yukarıdaki posta adresine yazılı olarak ya da kayıtlı elektronik posta (KEP), güvenli elektronik imza veya mobil imza ile başvurabilirsiniz; yukarıdaki e-posta adresine gönderilen başvurular da yanıtlanır. Başvurunuzda adınız soyadınız, yazılı başvurularda imzanız, T.C. kimlik numaranız (yabancıysanız uyruğunuz ile pasaport ya da kimlik numaranız), tebligata esas adresiniz, varsa e-posta adresiniz ve telefon numaranız ile talebinizin konusu bulunmalıdır. Başvurunuz en geç 30 gün içinde ücretsiz olarak yanıtlanır. Site kişisel veri saklamadığı için büyük olasılıkla size ait bir kayıt bulunmayacaktır; yine de her başvuru yanıtlanır.',
            'privacy.apply.github' => 'GitHub\'ın tuttuğu kayıtlarla ilgili taleplerinizi doğrudan GitHub\'a iletmeniz gerekir; site sahibi bu kayıtlara erişemez.',
            'privacy.apply.complaint' => 'Başvurunuzun reddedilmesi, verilen cevabı yetersiz bulmanız veya süresinde cevap verilmemesi hâlinde; cevabı öğrendiğiniz tarihten itibaren 30 gün ve her hâlde başvuru tarihinden itibaren 60 gün içinde Kişisel Verileri Koruma Kurulu\'na şikâyette bulunabilirsiniz (KVKK m. 14).',
            'privacy.content.h' => 'İçerik ve kullanım koşulları',
            'privacy.content.p' => 'Başlıklar ve özetler yayın organlarına aittir. Terazi herkese açık RSS akışlarından kısa alıntılar gösterir ve her zaman asıl habere bağlantı verir; haberler birkaç gün sonra silinir. İktidar yanlısı, bağımsız ve muhalefet yanlısı etiketleri bir değerlendirmedir, kesin bir olgu değildir; her birinin gerekçesi Yayın organları sayfasında yazar. Haberler otomatik olarak gruplanır ve bazen yanlış gruplanabilir. Site ücretsizdir ve olduğu gibi, herhangi bir garanti olmadan sunulur.',
            'privacy.changes.h' => 'Değişiklikler',
            'privacy.changes.p' => 'Sitenin ziyaretçilerle ilgili bilgileri işleme biçimi değişirse, bu metin değişiklik yürürlüğe girmeden önce güncellenir.',
            'privacy.updated' => 'Son güncelleme: 5 Ekim 2026.',
        ],
    ];

    private const DAYS = [
        'en' => ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        'tr' => ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
    ];
    private const MONTHS = [
        'en' => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        'tr' => ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
    ];

    public static function lang(): string
    {
        $l = (string)App::config('lang');
        return isset(self::STRINGS[$l]) ? $l : 'en';
    }

    public static function t(string $key, mixed ...$args): string
    {
        $s = self::STRINGS[self::lang()][$key] ?? self::STRINGS['en'][$key] ?? $key;
        return $args ? sprintf($s, ...$args) : $s;
    }

    /** "Monday, 5 October 2026" / "5 Ekim 2026 Pazartesi" */
    public static function longDate(int $ts): string
    {
        $l = self::lang();
        $d = self::DAYS[$l][(int)date('w', $ts)];
        $m = self::MONTHS[$l][(int)date('n', $ts) - 1];
        return $l === 'tr'
            ? date('j', $ts) . " $m " . date('Y', $ts) . " $d"
            : "$d, " . date('j', $ts) . " $m " . date('Y', $ts);
    }

    /** "5 Oct" */
    public static function shortDate(int $ts): string
    {
        return date('j', $ts) . ' ' . mb_substr(self::MONTHS[self::lang()][(int)date('n', $ts) - 1], 0, 3);
    }

    /** "5 Oct, 14:20" */
    public static function shortDateTime(int $ts): string
    {
        return self::shortDate($ts) . ', ' . date('H:i', $ts);
    }

    public static function ago(int $ts, ?int $now = null): string
    {
        $d = max(0, ($now ?? time()) - $ts);
        return match (true) {
            $d < 90 => self::t('ago.now'),
            $d < 3600 => self::t('ago.min', intdiv($d, 60)),
            $d < 86400 => self::t('ago.hour', intdiv($d, 3600)),
            default => self::t('ago.day', intdiv($d, 86400)),
        };
    }
}
